In [1]:
import pandas as pd
import numpy as np
import xarray as xr
import matplotlib.pyplot as plt
import os
from pathlib import Path

In [2]:
root_output_directory = "/Net/Groups/BSI/scratch/ppapastefanou/simulations/SimPHony/swiss_cc"
sorted(Path(root_output_directory).iterdir(), key=os.path.getmtime)

[PosixPath('/Net/Groups/BSI/scratch/ppapastefanou/simulations/SimPHony/swiss_cc/ex_con_2025_full_test'),
 PosixPath('/Net/Groups/BSI/scratch/ppapastefanou/simulations/SimPHony/swiss_cc/ex_con_2025_full_wide'),
 PosixPath('/Net/Groups/BSI/scratch/ppapastefanou/simulations/SimPHony/swiss_cc/ex_con_2025_full_wide_512'),
 PosixPath('/Net/Groups/BSI/scratch/ppapastefanou/simulations/SimPHony/swiss_cc/ex_con_2025_full_wide_2'),
 PosixPath('/Net/Groups/BSI/scratch/ppapastefanou/simulations/SimPHony/swiss_cc/01_ex_con_2025_full_wide_ltor'),
 PosixPath('/Net/Groups/BSI/scratch/ppapastefanou/simulations/SimPHony/swiss_cc/02_ex_con_2025_full_wide_ltor_beta_2times'),
 PosixPath('/Net/Groups/BSI/scratch/ppapastefanou/simulations/SimPHony/swiss_cc/02_ex_con_2025_full_gheart'),
 PosixPath('/Net/Groups/BSI/scratch/ppapastefanou/simulations/SimPHony/swiss_cc/03_ex_con_2025_full_gheart_weibull'),
 PosixPath('/Net/Groups/BSI/scratch/ppapastefanou/simulations/SimPHony/swiss_cc/04_ex_con_2025_full_gheart_logit'),
 PosixPath('/Net/Groups/BSI/scratch/ppapastefanou/simulations/SimPHony/swiss_cc/05_ex_con_2025_full_logit'),
 PosixPath('/Net/Groups/BSI/scratch/ppapastefanou/simulations/SimPHony/swiss_cc/06_ex_con_2025_full_logit_mean_one'),
 PosixPath('/Net/Groups/BSI/scratch/ppapastefanou/simulations/SimPHony/swiss_cc/07_ex_con_2025_full_logit_mean_one'),
 PosixPath('/Net/Groups/BSI/scratch/ppapastefanou/simulations/SimPHony/swiss_cc/08_ex_con_2025_full_logit_mean_one'),
 PosixPath('/Net/Groups/BSI/scratch/ppapastefanou/simulations/SimPHony/swiss_cc/09_ex_con_2025_full_logit_mean_one'),
 PosixPath('/Net/Groups/BSI/scratch/ppapastefanou/simulations/SimPHony/swiss_cc/10_ex_con_2025_full_logit_mean_one'),
 PosixPath('/Net/Groups/BSI/scratch/ppapastefanou/simulations/SimPHony/swiss_cc/11_ex_con_2025_full_logit_mean_one'),
 PosixPath('/Net/Groups/BSI/scratch/ppapastefanou/simulations/SimPHony/swiss_cc/12_ex_con_2025_full_logit_mean_one'),
 PosixPath('/Net/Groups/BSI/scratch/ppapastefanou/simulations/SimPHony/swiss_cc/13_ex_con_2025_full_logit_mean_one'),
 PosixPath('/Net/Groups/BSI/scratch/ppapastefanou/simulations/SimPHony/swiss_cc/14_ex_con_2025_full_logit_mean_one'),
 PosixPath('/Net/Groups/BSI/scratch/ppapastefanou/simulations/SimPHony/swiss_cc/15_ex_con_2025_full_logit_mean_one'),
 PosixPath('/Net/Groups/BSI/scratch/ppapastefanou/simulations/SimPHony/swiss_cc/16_ex_con_2025_full_logit_mean_one'),
 PosixPath('/Net/Groups/BSI/scratch/ppapastefanou/simulations/SimPHony/swiss_cc/17_ex_con_2025_full_logit_mean_one'),
 PosixPath('/Net/Groups/BSI/scratch/ppapastefanou/simulations/SimPHony/swiss_cc/18_ex_con_2025_full_logit_mean_one'),
 PosixPath('/Net/Groups/BSI/scratch/ppapastefanou/simulations/SimPHony/swiss_cc/19_ex_con_2025_full_logit_mean_one'),
 PosixPath('/Net/Groups/BSI/scratch/ppapastefanou/simulations/SimPHony/swiss_cc/20_ex_con_2025_full_logit_mean_one'),
 PosixPath('/Net/Groups/BSI/scratch/ppapastefanou/simulations/SimPHony/swiss_cc/21_ex_con_2025_full_logit_mean_one_wcont'),
 PosixPath('/Net/Groups/BSI/scratch/ppapastefanou/simulations/SimPHony/swiss_cc/23_ex_con_2025_full_logit_mean_one_wcont'),
 PosixPath('/Net/Groups/BSI/scratch/ppapastefanou/simulations/SimPHony/swiss_cc/25_ex_con_2025_full_logit_mean_one_wcont'),
 PosixPath('/Net/Groups/BSI/scratch/ppapastefanou/simulations/SimPHony/swiss_cc/26_ex_con_2025_full_logit_mean_one_wcont_TLP'),
 PosixPath('/Net/Groups/BSI/scratch/ppapastefanou/simulations/SimPHony/swiss_cc/27_ex_con_2025_full_logit_mean_one_wcont_TLP'),
 PosixPath('/Net/Groups/BSI/scratch/ppapastefanou/simulations/SimPHony/swiss_cc/28_ex_con_2025_full_logit_mean_one_wcont_TLP'),
 PosixPath('/Net/Groups/BSI/scratch/ppapastefanou/simulations/SimPHony/swiss_cc/29_ex_con_2025_full_logit_mean_one_wcont_TLP'),
 PosixPath('/Net/Groups/BSI/scratch/ppapastefanou/simulations/SimPHony/swiss_cc/30_ex_con_2025_full_logit_mean_one_wcont_TLP'),
 PosixPath('/Net/Groups/BSI/scratch/ppapastefanou/simulations/SimPHony/swiss_cc/31_LHS_TLP'),
 PosixPath('/Net/Groups/BSI/scratch/ppapastefanou/simulations/SimPHony/swiss_cc/32_LHS_TLP'),
 PosixPath('/Net/Groups/BSI/scratch/ppapastefanou/simulations/SimPHony/swiss_cc/33_LHS_TLP'),
 PosixPath('/Net/Groups/BSI/scratch/ppapastefanou/simulations/SimPHony/swiss_cc/34_LHS_TLP'),
 PosixPath('/Net/Groups/BSI/scratch/ppapastefanou/simulations/SimPHony/swiss_cc/35_LHS_TLP'),
 PosixPath('/Net/Groups/BSI/scratch/ppapastefanou/simulations/SimPHony/swiss_cc/36_LHS_TLP'),
 PosixPath('/Net/Groups/BSI/scratch/ppapastefanou/simulations/SimPHony/swiss_cc/37_LHS_no_TLP'),
 PosixPath('/Net/Groups/BSI/scratch/ppapastefanou/simulations/SimPHony/swiss_cc/38_LHS_TLP'),
 PosixPath('/Net/Groups/BSI/scratch/ppapastefanou/simulations/SimPHony/swiss_cc/39_LHS_TLP'),
 PosixPath('/Net/Groups/BSI/scratch/ppapastefanou/simulations/SimPHony/swiss_cc/40_LHS_TLP'),
 PosixPath('/Net/Groups/BSI/scratch/ppapastefanou/simulations/SimPHony/swiss_cc/41_LHS_TLP'),
 PosixPath('/Net/Groups/BSI/scratch/ppapastefanou/simulations/SimPHony/swiss_cc/42_LHS_TLP'),
 PosixPath('/Net/Groups/BSI/scratch/ppapastefanou/simulations/SimPHony/swiss_cc/43_LHS_TLP'),
 PosixPath('/Net/Groups/BSI/scratch/ppapastefanou/simulations/SimPHony/swiss_cc/44_LHS_TLP'),
 PosixPath('/Net/Groups/BSI/scratch/ppapastefanou/simulations/SimPHony/swiss_cc/46_LHS_no_TLP'),
 PosixPath('/Net/Groups/BSI/scratch/ppapastefanou/simulations/SimPHony/swiss_cc/45_LHS_TLP'),
 PosixPath('/Net/Groups/BSI/scratch/ppapastefanou/simulations/SimPHony/swiss_cc/.vscode')]

In [3]:
# root_output_directory = "/Users/pp/data/Simulations/A08_SimPHony/swiss/excon"
# scenario_name = "old_params_extensive"

In [3]:
scenario_name = "29_ex_con_2025_full_logit_mean_one_wcont_TLP"

root_output_directory = "/Net/Groups/BSI/scratch/ppapastefanou/simulations/SimPHony/"
scenario_name = "45_LHS_TLP"

input_path = os.path.join(root_output_directory, scenario_name, 'input')
output_path = os.path.join(root_output_directory, scenario_name, 'output')
post_path = os.path.join(root_output_directory, scenario_name, 'post')

In [4]:
vars = ['psi_leaf_50_close', 'd_50_close','stem_hydraulic_capacitance', 'k_xylem_sat','huber_value',  'leaf_hydraulic_capacitance', 'psi50_xylem' , 'alpha','g0', 'g1', 'k_soil_sat0', 'psi_soil_sat0','jackson_root_beta',  'pore_0',  'root_area_index', 'wcont_sigma_deviation','g_stem_res', 'vmax25' , 'jmax25']
vars_plant = ['stem_hydraulic_capacitance', 'k_xylem_sat','huber_value', 'leaf_hydraulic_capacitance', 'psi50_xylem' ,'g0','jackson_root_beta', 'alpha']

In [5]:
df = pd.read_csv(os.path.join(post_path, "aggregated_out.csv"))
df['alpha'] = df['g_stem_res']/ df['g0']
df.sort_values(by=['RMSE_MAX'], inplace=True, ascending=True)
df = df[(df['RMSE_MAX'] < 1.5)]
print(df.shape)
df_grp = df.groupby(['id'])[vars].mean()

dead_ids =[0,3,6,7]
dfs =df[df['sid'] == 0]
dfs.sort_values(by=['alive_mean'], inplace=True, ascending=True)
dfs.to_csv(os.path.join(post_path, "Alive.csv"))
for i in range(1,5):
    dfs =df[df['sid'] == i]
    dfs.sort_values(by=[f't{dead_ids[i - 1]}'], inplace=True, ascending=True)
    print(dfs.shape)
    dfs.to_csv(os.path.join(post_path, f"Dead{i}.csv"))

FileNotFoundError: [Errno 2] No such file or directory: '/Net/Groups/BSI/scratch/ppapastefanou/simulations/SimPHony/45_LHS_TLP/post/aggregated_out.csv'

In [12]:
df

,Unnamed: 0,index,id,root_area_index,canopy_height,dts,dts_input,verbose,max_psi_leaf_change_per_hour,minimum_psi_leaf_multiplier,...,t9,t10,t11,t12,t13,alive_mean,target_rmse,RMSE_MAX,sid,alpha
459,4,658,91,6.189604,35,1800.0,1800,False,1.0,1.75,...,6.078590,3.812660,4.064461,3.782487,3.765620,4.187594,0.946042,1.163557,4,0.135521
456,1,507,91,5.215496,35,1800.0,1800,False,1.0,1.75,...,7.052276,3.846480,4.056369,3.822341,3.740244,4.331087,0.946042,1.163557,1,0.117570
457,2,419,91,7.197565,35,1800.0,1800,False,1.0,1.75,...,2.066727,1.140034,1.233117,1.101200,0.994358,1.275866,0.946042,1.163557,2,0.107858
455,0,254,91,6.870787,35,1800.0,1800,False,1.0,1.75,...,0.239255,0.622165,0.593321,0.646091,0.577947,0.558508,0.946042,1.163557,0,0.128828
458,3,507,91,5.215496,35,1800.0,1800,False,1.0,1.75,...,7.052276,3.846480,4.056369,3.822341,3.740244,4.331087,0.946042,1.163557,3,0.117570
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1112,2,85,222,8.587234,35,1800.0,1800,False,1.0,1.75,...,2.269996,1.205945,1.287711,1.174410,1.063522,1.356864,1.144614,1.397932,2,0.012068
1110,0,409,222,7.650440,35,1800.0,1800,False,1.0,1.75,...,0.228097,0.703341,0.649674,0.727496,0.653440,0.611326,1.144614,1.397932,0,0.010185
1113,3,155,222,7.630239,35,1800.0,1800,False,1.0,1.75,...,5.702539,3.525747,3.756938,3.500934,3.480382,3.883691,1.144614,1.397932,3,0.011220
1114,4,639,222,7.238136,35,1800.0,1800,False,1.0,1.75,...,5.928103,3.698449,3.942344,3.669113,3.651684,4.066231,1.144614,1.397932,4,0.010714
1111,1,836,222,7.564693,35,1800.0,1800,False,1.0,1.75,...,3.898456,2.045835,2.193233,2.007024,1.928695,2.329079,1.144614,1.397932,1,0.011045

In [8]:
df['RMSE_MAX'].iloc[0]

np.float64(1.1195318615143008)

In [9]:
df['RMSE_MAX'].iloc[1000]

np.float64(1.489528734909353)

In [10]:
df['alive_mean'].iloc[0]

np.float64(3.9921085393838176)

In [8]:
df[['alive_mean','t6', 't5', 'RMSE_MAX', 'id', 'sid']]

       alive_mean        t6        t5  RMSE_MAX    id  sid
7761     2.396878  1.585008  4.023215  1.059908  1552    1
7762     1.186208  2.230637  2.038813  1.059908  1552    2
7763     4.167617  0.904709  6.378804  1.059908  1552    3
7764     4.505040  2.009306  6.442451  1.059908  1552    4
7760     0.508756  2.969751  0.350117  1.059908  1552    0
...           ...       ...       ...       ...   ...  ...
25673    4.299700  0.871612  6.599501  1.099483  5134    3
25670    0.527752  2.913209  0.310299  1.099483  5134    0
25674    4.530023  1.965680  6.514573  1.099483  5134    4
25672    1.074299  2.370085  1.793297  1.099483  5134    2
25671    4.480919  1.339001  7.744884  1.099483  5134    1

[140 rows x 6 columns]

In [7]:
pd.read_csv("/Net/Groups/BSI/scratch/ppapastefanou/simulations/SimPHony/swiss_cc/26_ex_con_2025_full_logit_mean_one_wcont_TLP/output/parameters_f0.csv87")

,Unnamed: 0,index,id,root_area_index,canopy_height,dts,dts_input,verbose,max_psi_leaf_change_per_hour,minimum_psi_leaf_multiplier,...,t6,t7,t8,t9,t10,t11,t12,t13,alive_mean,target_rmse
0,0,333,333,7.303459,35,1800.0,1800,False,1.0,1.75,...,3.252127,2.272290,0.710227,0.262686,0.750741,0.707002,0.765253,0.671653,0.648600,0.998276
1,0,428,428,6.963073,35,1800.0,1800,False,1.0,1.75,...,1.068188,1.252175,7.660265,7.831438,4.298675,4.525709,4.276541,4.198179,4.832755,0.998276
2,0,957,957,5.884408,35,1800.0,1800,False,1.0,1.75,...,2.675596,2.052022,1.367123,2.096074,1.136459,1.206427,1.109999,0.998976,1.269161,0.998276
3,0,634,634,6.943132,35,1800.0,1800,False,1.0,1.75,...,0.906969,1.455945,6.071651,6.235083,3.428173,3.621198,3.409173,3.346515,3.857972,0.998276
4,0,518,518,7.072359,35,1800.0,1800,False,1.0,1.75,...,1.924185,0.556429,6.089753,6.253297,3.932413,4.186807,3.903267,3.885771,4.314775,0.998276

In [10]:
for var in vars:
    fig = plt.figure(figsize=(6,6))
    ax = fig.add_subplot(1,1,1)
    ax.hist(df_grp[var], alpha=1.0, bins = 20)
    ax.set_xlabel(var)
    plt.savefig(f"{post_path}/mean_hist_{var}.png")
    plt.close(fig)

In [12]:
df_grp['psi_soil_sat0'].describe()

count    12677.000000
mean        -1.872398
std          0.204552
min         -2.438638
25%         -2.017353
50%         -1.885340
75%         -1.735528
max         -1.173710
Name: psi_soil_sat0, dtype: float64

In [13]:
dv = df[vars]
dv['leaf_hydraulic_capacitance'] = np.log10(dv['leaf_hydraulic_capacitance'])
df_norm=(dv-dv.mean())/dv.std()
df_norm['sid'] = df['sid']

/tmp/ipykernel_2629456/3013431960.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dv['leaf_hydraulic_capacitance'] = np.log10(dv['leaf_hydraulic_capacitance'])

In [25]:
df

,Unnamed: 0,index,id,root_area_index,canopy_height,dts,dts_input,verbose,max_psi_leaf_change_per_hour,minimum_psi_leaf_multiplier,...,t8,t9,t10,t11,t12,t13,alive_mean,target_rmse,RMSE_MAX,sid
431,1,15,86,7.762377,35,1800.0,1800,False,1.0,1.75,...,3.407834,3.692183,2.065216,2.238339,2.047149,1.993478,2.337537,2.312688,3.899828,1
432,2,98,86,7.326279,35,1800.0,1800,False,1.0,1.75,...,2.735267,2.932828,1.651059,1.800723,1.617456,1.588838,1.871917,2.312688,3.899828,3
433,3,18,86,5.856092,35,1800.0,1800,False,1.0,1.75,...,6.442311,6.607900,3.919388,4.166091,3.893103,3.875014,4.357038,2.312688,3.899828,4
434,4,31,86,8.236665,35,1800.0,1800,False,1.0,1.75,...,7.438825,7.609121,4.603923,4.885101,4.577354,4.557050,5.092177,2.312688,3.899828,4
430,0,98,86,7.326279,35,1800.0,1800,False,1.0,1.75,...,2.735267,2.932828,1.651059,1.800723,1.617456,1.588838,1.871917,2.312688,3.899828,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
324,4,70,64,6.336561,35,1800.0,1800,False,1.0,1.75,...,7.355023,7.524974,5.810580,6.178284,5.762877,5.755512,6.131852,7.956747,11.808308,4
322,2,53,64,6.078700,35,1800.0,1800,False,1.0,1.75,...,6.532849,6.698927,5.395102,5.750756,5.370029,5.354374,5.667988,7.956747,11.808308,3
321,1,53,64,6.078700,35,1800.0,1800,False,1.0,1.75,...,6.532849,6.698927,5.395102,5.750756,5.370029,5.354374,5.667988,7.956747,11.808308,1
323,3,70,64,6.336561,35,1800.0,1800,False,1.0,1.75,...,7.355023,7.524974,5.810580,6.178284,5.762877,5.755512,6.131852,7.956747,11.808308,4
320,0,53,64,6.078700,35,1800.0,1800,False,1.0,1.75,...,6.532849,6.698927,5.395102,5.750756,5.370029,5.354374,5.667988,7.956747,11.808308,0

In [ ]:
pd

,psi_leaf_50_close,d_50_close,stem_hydraulic_capacitance,k_xylem_sat,huber_value,leaf_hydraulic_capacitance,psi50_xylem,g0,g1,k_soil_sat0,psi_soil_sat0,jackson_root_beta,pore_0,root_area_index,wcont_sigma_deviation,g_stem_res,vmax25,jmax25,sid
37470,-1.842752,-0.554372,-0.370560,0.485961,-0.880111,-2.286066,0.637772,1.716773,1.577441,2.206818,0.386899,-1.022941,1.384049,-0.568567,1.195950,1.597305,-1.503899,0.232302,0
37471,0.617266,-0.517465,-0.267512,0.249457,-0.232585,-2.228321,-1.749779,0.756942,1.788220,-0.593095,0.503605,-1.576924,0.155565,0.734366,-0.018786,0.780097,-1.547156,-0.423482,1
37474,0.037802,-0.958128,-0.403252,-0.006440,-0.274184,-1.439697,1.154656,0.415688,0.077485,-0.581892,-0.930901,1.011914,0.729367,-0.570784,0.907257,0.915320,0.029872,-1.250959,4
37473,-1.028345,-0.477401,-0.095790,0.759186,-0.319614,-1.377707,1.025546,0.451646,1.521516,-0.400047,0.190721,0.502157,-0.592277,0.202859,-0.704322,0.388885,-1.228816,-0.616687,4
37472,0.727855,-0.673374,-0.052052,0.777309,-0.419855,-1.368929,-1.747454,0.683759,1.342992,-0.540424,0.185693,-0.940592,1.390386,-0.447854,0.409006,1.517512,-0.629858,0.543387,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39166,0.757879,-0.856471,0.580705,0.555654,-0.687930,-1.318359,-1.189805,-0.476661,-1.168033,-0.301527,-0.915528,-0.581273,-1.555303,1.181415,-0.731942,1.004744,1.374202,0.522626,1
39168,-0.398014,-0.977697,1.156425,0.074514,-0.548578,-1.305201,1.046575,0.277653,-1.617967,0.130855,-1.810922,0.522710,1.402644,2.192642,-1.174328,0.753976,0.702023,1.337883,4
39165,-1.068722,-0.735749,1.520197,0.196514,-1.091123,-0.548967,0.036351,0.019427,-1.084719,2.746956,1.437315,-1.597829,0.405211,1.462604,0.759871,0.082774,1.194451,1.591378,0
39169,-0.861404,-0.626078,1.569949,0.547786,-0.951895,-0.885794,0.989521,0.519590,-1.508095,0.742687,-1.458126,-1.308610,-1.216471,1.013764,-0.973331,0.108134,0.475138,-0.110235,4
39167,0.676751,-0.750497,1.729223,0.414879,-0.526401,-0.995855,-0.483271,-0.280084,-1.377851,-0.537843,0.787090,1.377262,-0.997593,2.081256,0.811177,1.103533,2.355855,0.957710,3

In [30]:
for var in vars:
   #if (var == 'id') | (var == 'sid'):
   #     continue        
    fig = plt.figure(figsize=(10,10))
    for sid in [1,3,4]:
        dfh = pd.DataFrame()
        dfh[var] = df_norm[df_norm['sid'] == sid][var].values - df_norm[df_norm['sid'] == 0][var].values
        ax = fig.add_subplot(2,2,sid)
        ax.hist(dfh[var], alpha=1.0, bins = 20)
        ax.set_xlabel(var)
        ax.text(0.95, 0.95, f"Mean: {np.round(dfh[var].mean(), 4)}",
        verticalalignment ='bottom',
        horizontalalignment ='right',
        transform = ax.transAxes)
    plt.savefig(f"{post_path}/sid_hist_{var}.png")
    plt.close(fig)

NameError: name 'df_norm' is not defined